config/routes.rb
Rails.application.routes.draw do  

  root to: 'frontend#index'

  resources :reservations, only:[:new, :create]

  get "habitacion/:id", to: "frontend#show_room", as: "show_room"
  
  #get "lugar/:id", to: "frontend#show_place", as: "show_place"

  mount InyxCatalogRails::Engine, :at => '', as: 'catalog'

  devise_for :users, skip: [:registration]

  resources :admin, only: [:index]

  scope :admin, except: [:new, :create] do
    resources :reservations do
      collection do
        post '/delete', to: 'reservations#delete'
        get '/', to: 'reservations#index', as: 'index'
      end
    end
  end
  scope :admin do
  	resources :users do
  		collection do
	  		post '/delete', to: 'users#delete'
  		end
  	end
  end
end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
	layout 'layouts/frontend/application'  
  def index
  	Location.add(request.remote_ip) 
  	@items = items_hash 
    @rooms = InyxCatalogRails::Catalog.where(public: true, category: "Habitaciones")	
  end

  def show_room
  	Location.add(request.remote_ip) 
  	@room = InyxCatalogRails::Catalog.where(id: params[:id], category: "Habitaciones").first
  end

  def show_place
    Location.add(request.remote_ip) 
    @place = InyxCatalogRails::Catalog.where(id: params[:id], category: "Lugares").first
  end

  private
  	def items_hash
  		items = [  		
	  		["PASEOS TURÍSTICOS", "/assets/frontend/paseos.png", "6"], 
	  		["SUITES", "/assets/frontend/suite.png", "1", "h"], 		
	  		["SENDEROS DE INTERPRETACIÓN", "/assets/frontend/sendero.png", "7"],
	  		["HABITACIONES SENCILLAS", "/assets/frontend/sencilla.png", "2", "h"], 
	  		["HABITACIONES DOBLES", "/assets/frontend/doble.png", "3", "h"],  		
	  		["HABITACIONES FAMILIARES", "/assets/frontend/familiar.png", "4", "h"],
	  		["HABITACIONES MULTIPLES", "/assets/frontend/multiple.png", "5", "h"],
	  	]	
	  	return items 
  	end
end

app/helpers/frontend_helper.rb
module FrontendHelper
end

app/views/frontend/_creditos.html.haml
.green-line
	Posada Tierra de Aves - Todos los derechos reservados.
.white-line
	.container
		.row
			.col-lg-6.col-md-6.col-sm-6.col-xs-6
				Desarrollado por
				=link_to "http://slicegroup.xyz/" do 
					= image_tag "frontend/slice.png", width: "60px"
			.col-lg-6.col-md-6.col-sm-6.col-xs-6
				.pull-right.muffin
					Diseñado por
					=link_to "http://studiomuffin.com/" do
						= image_tag "frontend/muffin.png", width: "60px"

app/views/frontend/_experiencia.html.haml
#experiencia-container
.container
	.row
		.col-lg-4.col-md-4.hidden-sm.hidden-xs
			.image-experiencia.pull-right
		.col-lg-8.col-md-8.col-sm-12.col-xs-12
			%center.text-exp
				¡Cuéntanos tu experiencia con nosotros!
				= image_tag "frontend/tripadvisor.png", class: "tipadvisor"

app/views/frontend/_footer.html.haml
.container.container-footer
	.row
		.col-lg-5.col-md-5.col-sm-5
			%h2 CONTACTOS
			.line-footer
			%p
				Email: reservas@tierradeavesposada.com
			%p
				Teléfono: +58 0261-511.07.51
			.row.row-social
				.col-lg-4.col-md-4.col-sm-4.col-xs-4
					.social.facebook
						%center
							= link_to "https://facebook.com/tierradeavesp", target:"_blank" do
								%i.fa.fa-facebook
				.col-lg-4.col-md-4.col-sm-4.col-xs-4
					.social.instagram
						%center
							= link_to "https://instagram.com/tierradeavesp/", target:"_blank" do
								%i.fa.fa-instagram
				.col-lg-4.col-md-4.col-sm-4.col-xs-4
					.social.twitter
						%center
							= link_to "https://twitter.com/tierradeavesp", target:"_blank" do
								%i.fa.fa-twitter
		.col-lg-7.col-md-7.col-sm-7.text-footer-2
			.text
				%h2 DIRECCIÓN
				.line-footer.left 
				%p
					Av. Principal de la población Quisiro. Parroquia Faria,
				%p
					Municipio Miranda, Estado Zulia
			#map_canvas
			.logo-aves
				= image_tag "frontend/home.png", width: "200px", class: "left"
= render "creditos"

app/views/frontend/_habitaciones.html.haml
.container
  .title-section
    HABITACIONES
  .divisor-section
  .text-section
    %p Que tipos de habitaciones ofrecemos

  .owl-carousel
    -@rooms.each do |room|
      %div{class:"contenedordetalle"}
        %p{class:"titulo"}
          = I18n.transliterate(room.name).upcase
        .img-responsive{style: "background-image: url(#{room.cover})"}
          .mask-room
        = link_to show_room_path(room.id), class: "btn-reservation" do
          VER DETALLE 

:javascript
  $(document).on('ready page:load', function(arguments){
    $(".owl-carousel").owlCarousel({
      autoPlay: true,
      items : 3,
      itemsDesktop : [1199,3],
      itemsDesktopSmall : [980,3],
      itemsTablet: [768,2],
      itemsTabletSmall: [768,2],
      itemsMobile : [479,1],
      responsive: true,
      responsiveRefreshRate : 200,
      responsiveBaseWidth: window,
      navigation : true,
      navigationText: [
      "<i class='fa fa-arrow-left'></i>",
      "<i class='fa fa-arrow-right'></i>"
      ],
      pagination: false
    })
  });

app/views/frontend/_home.html.haml
.title-home ¡VIVE LA NATURALEZA!	
.responsive-container
	.img-container
		.centered				
			%img.image-home{src: "assets/frontend/home.png", width: "378px"}
			.reservation-box.hidden-xs
				= form_tag new_reservation_path, method: :get do |f|
					.row
						.col-lg-4.col-md-4.col-sm-4#colunm-home
							.input-home
								= text_field_tag :check_in, params[:check_in], :placeholder => "Check-in", id: "reservation_check_in"
								%i.fa.fa-calendar
						.col-lg-4.col-md-4.col-sm-4#colunm-home
							.input-home
								= text_field_tag :check_out, params[:check_out], :placeholder => "Check-out", id: "reservation_check_out"
								%i.fa.fa-calendar
						.col-lg-4.col-md-4.col-sm-4
							%button.btn-reservation
								RESERVAR

			%center
				.row#home-social
					.col-lg-4.col-md-4.col-sm-4.col-xs-4
						.social#home-social-icon.facebook
							%center
								= link_to "www.facebook.com/tierradeavesp", target:"_blank" do
									%i.fa.fa-facebook
					.col-lg-4.col-md-4.col-sm-4.col-xs-4
						.social#home-social-icon.instagram
							%center
								= link_to "https://instagram.com/tierradeavesp/", target:"_blank" do
									%i.fa.fa-instagram
					.col-lg-4.col-md-4.col-sm-4.col-xs-4
						.social#home-social-icon.twitter
							%center
								= link_to "https://twitter.com/tierradeavesp", target:"_blank" do
									%i.fa.fa-twitter
			.button-down
				= link_to "#" do
					%img.down{src: "assets/frontend/down.png", width: "30px"}

app/views/frontend/_porque.html.haml
.container
  .title-section
    TIERRA DE AVES
  .divisor-section
  .text-section
    %p Uno de los principales atractivos de Quisiro es la Playa Oribor cuyo nombre corresponde al Cacique Indigena Oribor quien resguardo por muchos años toda la zona costera que comprende San Carlos, Zapara, Toas y la costa mirandina, Oribor en su lengua original quiere decir “donde habitan las aves” o “tierra de aves”, por está razón y por la presencia del refugio de fauna silvestre “Ciénaga de los Olivitos” un hábitat donde se pueden observar más de 113 especies de aves, así como mamíferos, reptiles y diversidad de fauna acuática.

  %ul.clean-list.facilities-items.text-center.row
    - @items.each do |item|
      %li.col-md-3.col-sm-4
        .facility-item
          .shape-square.mask
            %figure
              - if item[3] == "h"
                %a{:href => "/habitacion/#{item[2]}"}
                  %img{:alt => "facilities", :src => "#{item[1]}"}
              - else
                %a
                  %img{:alt => "facilities", :src => "#{item[1]}"}
              
          %span.uppercase.font-300.text-white.facility-text
            = item[0]
            
  .titles.hidden-xs
    %ul.scrollable
      %li#text-1
        CONECTA CON LA NATURALEZA
      %li#text-2
        UN ESPACIO ÚNICO PARA EL DESCANSO
      %li#text-3
        CONOCE QUISIRO Y SUS ATRACTIVOS ÚNICOS

   

app/views/frontend/index.html.haml
#home   
	=	render 'home'
#navigation   
	=	render 'layouts/frontend/navigation'
#porque   
	=	render 'porque'
#habitaciones
	=	render 'habitaciones'
#experiencia
	=	render 'experiencia'
#footer
	=	render 'footer'

:javascript
	function scrollToAnchor(aid, id){
		var aTag = $("#"+id);
		$('html,body').animate({scrollTop: aTag.offset().top},'slow');
	}

	$(".down").on('click', function() {
		scrollToAnchor(this.id, "navigation");
	});

app/views/frontend/show_place.html.haml
#navigation
	= render 'layouts/frontend/navigation'
#rooms-image
#show_room
	.container
		.row
			.col-lg-6
				%h2 
					= @place.name
				.line-room
				%p{align: "justify"}
					= @place.description.html_safe if @place.description 
			.col-lg-6
				- unless @place.attachments.blank?
					#carousel-rooms.carousel.slide{"data-ride" => "carousel"}
						/ Wrapper for slides
						.carousel-inner{:role => "listbox"}
							- @place.attachments.each_with_index do |attachment, index|
								- if index == 0
									.item.active
										.image-carousel{style: "background-image: url(#{attachment.image})"}
								- else
									.item
										.image-carousel{style: "background-image: url(#{attachment.image})"}
							
						/ Controls
						%a.left.carousel-control{"data-slide" => "prev", :href => "#carousel-rooms", :role => "button"}
							%i.fa.fa-chevron-left{"aria-hidden" => "true"}
							%span.sr-only Previous
						%a.right.carousel-control{"data-slide" => "next", :href => "#carousel-rooms", :role => "button"}
							%i.fa.fa-chevron-right{"aria-hidden" => "true"}
							%span.sr-only Next
						
#experiencia
	= render 'experiencia'
#footer
	= render "creditos"

	

app/views/frontend/show_room.html.haml
#navigation
	= render 'layouts/frontend/navigation'
#rooms-image
#show_room
	.container
		.row
			.col-lg-6
				%h2 
					= I18n.transliterate(@room.name).upcase
				.line-room
				%p{align: "justify"}
					= @room.description.html_safe if @room.description 
				
				= link_to	new_reservation_path, class: "btn-reservation", id: "btn-room" do
					RESERVAR
			.col-lg-6
				- unless @room.attachments.blank?
					#carousel-rooms.carousel.slide{"data-ride" => "carousel"}
						/ Wrapper for slides
						.carousel-inner{:role => "listbox"}
							- @room.attachments.each_with_index do |attachment, index|
								- if index == 0
									.item.active
										.image-carousel{style: "background-image: url(#{attachment.image})"}
								- else
									.item
										.image-carousel{style: "background-image: url(#{attachment.image})"}
							
						/ Controls
						%a.left.carousel-control{"data-slide" => "prev", :href => "#carousel-rooms", :role => "button", style: "background-image:none"}
							%i.fa.fa-chevron-left{"aria-hidden" => "true"}
							%span.sr-only Previous
						%a.right.carousel-control{"data-slide" => "next", :href => "#carousel-rooms", :role => "button", style: "background-image:none"}
							%i.fa.fa-chevron-right{"aria-hidden" => "true"}
							%span.sr-only Next
				- else
					.image-carousel{style: "background-image: url(#{@room.cover})"}
						
#experiencia
	= render 'experiencia'
#footer
	= render "creditos"