config/routes.rb
Rails.application.routes.draw do  

  root to: 'frontend#index'

  resources :reservations, only:[:new, :create]

  get "habitacion/:id", to: "frontend#show_room", as: "show_room"
  
  #get "lugar/:id", to: "frontend#show_place", as: "show_place"

  mount InyxCatalogRails::Engine, :at => '', as: 'catalog'

  devise_for :users, skip: [:registration]

  resources :admin, only: [:index]

  scope :admin, except: [:new, :create] do
    resources :reservations do
      collection do
        post '/delete', to: 'reservations#delete'
        get '/', to: 'reservations#index', as: 'index'
      end
    end
  end
  scope :admin do
  	resources :users do
  		collection do
	  		post '/delete', to: 'users#delete'
  		end
  	end
  end
end

app/models/user.rb
require 'elasticsearch/model'
class User < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  before_save :create_permalink, on: :create
  #before_save :index_elasticsearch_document, on: :update
  rolify
  validates_presence_of :name, :role_ids

  #has_many :posts, dependent: :destroy relation posts
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    def as_json(options = {})
      {
        id: self.id,
        role_name: role_name,
        rol: self.roles.first.id,
        email: self.email,
        name: self.name,
        permalink: self.permalink,
        created_at: self.created_at,
        sign_in_count: self.sign_in_count
      }
    end

  def role_name
    self.roles.first.name
  end
  
  def self.group_by_roles
    rtrn = {}
    [:admin, :moderator, :redactor].each do |rol|
      rtrn[rol] = User.with_role(rol).count
    end
    rtrn
  end

  def self.get_id(permalink)
    User.find_by_permalink(permalink).id
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [:role_name, :name, :email, :permalink] , operator: :and }  }, sort: { id: "desc" }, size: User.count }
  end

  #params[:search] is false
  def self.index(current_user)
    User.where("id != #{current_user.id}").order("created_at DESC")
  end

  #params[:search] is true
  def self.index_search(objects, current_user)
    objects.where("id != #{current_user.id}").order("created_at DESC")
  end

  #params[:search] is true
  def self.index_total(objects, current_user)
    objects.where("id != #{current_user.id}").count
  end

  def self.route_index
    "/admin/users"
  end

  def index_elasticsearch_document
    self.__elasticsearch__.index_document
  end

  def create_permalink
    self.permalink = self.name.downcase.parameterize+"-"+SecureRandom.hex(4)
  end

  def self.multiple_destroy(ids, current_user)
    ids.each do |id|
      raise CanCan::AccessDenied.new("Access Denied", :delete, User) if id.to_i == current_user.id
    end
    User.destroy ids
  end

end

User.import

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])

    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    respond_to do |format|
      if @user.update_attributes(user_params)
        @user.__elasticsearch__.index_document
        format.html { redirect_to user_path(@user), :notice => t("notification.update") }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        @user.add_role Role.find(user_params[:role_ids]).name
        format.html { redirect_to user_path(@user), notice: t("notification.create") }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => t("notification.delete")
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :role_ids, :encrypted_password)
  end

end

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
	.container_form	
		.title_form
			Datos de usuario
		.form-p
			.input#name{ class: "#{@user.name.blank? ? 'input-false' : 'input-great' }"}
				= f.input :name, label: 'Nombre', input_html: { class: 'input_form', id: "input-name", "ng-focus" => "inputFocus('name')", "ng-blur" => "inputBlur('name')" }
			.input#email{ class: "#{@user.email.blank? ? 'input-false' : 'input-great' }"}
				= f.input :email, label: 'Email', input_html: { class: 'input_form', id: "input-email", "ng-focus" => "inputFocus('email')", "ng-blur" => "inputBlur('email')" }
			.input.input-false#roles{ class: "#{@user.role_ids.count==0 ? 'input-false' : 'input-great' }"}
				= f.input :role_ids, label: 'Roles', collection: Role.all, input_html: { class: "input_form", id: "input-roles", "ng-focus" => "inputFocus('roles')", "ng-blur" => "inputBlur('roles')" }
				= #raw t('devise.announce_password') if params[:action] == 'edit' or params[:action] == 'update'
			.input.input-false#password{ class: "#{@user.password.blank? ? 'input-false' : 'input-great' }"}
				= f.input :password, label: 'Contraseña', input_html: { class: 'input_form', id: "input-password", "ng-focus" => "inputFocus('password')", "ng-blur" => "inputBlur('password')" }
			.input.input-false#confirmation{ class: "#{@user.password_confirmation.blank? ? 'input-false' : 'input-great' }"}
				= f.input :password_confirmation, label: 'Confirmación de contraseña', input_html: { class: 'input_form', id: "input-confirmation", "ng-focus" => "inputFocus('confirmation')", "ng-blur" => "inputBlur('confirmation')"}
		%br
		.panel-footer
			.form-actions
				= f.button :submit, "Guardar", class: "pull-right btn btn-warning"
			.clearfix

app/views/users/_modal_role.html.haml
.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1",:id => "role-options-{{object.id}}" }
	.modal-dialog
		.modal-content
			= form_tag "{{update_path(object.id)}}",  method: "PUT" do
				.modal-header
					%button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
					%h3#myModalLabel.modal-title 
						Roles
				.modal-body
					%center
						- Role.all.each do |rol|
							= radio_button_tag "user[role_ids]", rol.id, false, "ng-model" => "object.rol"
							= label_tag "user[role_ids]", t("admin.roles.#{rol.name}")
				.modal-footer
					%button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Cerrar
					= submit_tag "Asignar Rol", :class => "btn btn-warning"

app/views/users/_view_lg_md.html.haml
%div{ 'ng-init'=>"init(#{@objects.to_json}, '/admin/users', '#{params[:search]}', #{@total_rows}, #{Kaminari.config.default_per_page})", "resize" => "" }
	.grid-content
		.col-lg-9.col-md-9{ style: "padding:0px;" }	
			.list-wrapper
				.panel.panel-default
					- flash.each do |name, msg|
						- if msg.is_a?(String)
							%div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'} pull-right", id: "message_alerts"}
								%button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
								= content_tag :div, msg, :id => "flash_#{name}"
					.panel-heading#list-heading
						- if can? :new, User
							= link_to new_user_path, title: t("admin.buttons.new"), class: "btn btn-default btn-action" do
								%i.fa.fa-plus
						%a.btn.btn-default.btn-action{"ng-click" => "refresh()", "ng-disabled" => "pagesItemsSelected[currentPageServer].length != 0", :title => t("admin.buttons.refresh") }
							%i.fa.fa-refresh#icon-refresh{'ng-show'=>"!loadingRefresh"}
							%i.fa.fa-refresh.fa-spin{'ng-show'=>"loadingRefresh"}
						- if can? :delete, User
							%a.btn.btn-default.btn-action{"ng-show" => "objects.length", "ng-click" => "allSelected(objects)", :title => t("admin.buttons.select_all") }
								%i.fa.fa-square-o{"ng-show" => "!btnDelete"}
								%i.fa.fa-check-square-o{ "ng-show" => "btnDelete" }	
							%a.btn.btn-default.btn-action#btn-delete{ "ng-show" => "btnDelete", "ng-click" => "destroy('¿Estas seguro de querer eliminar los usuarios seleccionados?')", :title => t("admin.buttons.trash") }
								%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingDelete" }
								%i.fa.fa-trash-o{ 'ng-show' => "!loadingDelete" }
						.paginator.pull-right{ "ng-show" => "objects.length > 0"}
							%button.btn.btn-default.pull-right.hidden-xs{'disabled'=>"", style:"color:#000; margin-left:3px;"}
								Página {{currentPage+1}} de {{numberOfPages()}}
							%a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
								%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
								%i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
							%a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
								%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
								%i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
					.panel-body{ style: "border-right: 1px solid #e7e7e7;" }
						#table-scroll
							%table.grid{style: "width:100%"}
								%tbody
									%tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object)", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize"}
										- if can? :delete, User
											%td{ width: "1px;" }
												.checkboxFour
													%input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
													%label{ for: "check-{{object.id}}" }
														%span
										%td {{ object.name }}
										%td {{ object.email }}
										%td {{ object.role_name | titlecase }}
										%td
											%a{"data-toggle" => "modal", :href => "#role-options-{{object.id}}", :type => "button"}= t("user.change-rol")
											= render "modal_role"
									%tr{"ng-show" => "!objects.length"}
										%td{:style => "width:100%"}
											%center
												%i.fa.fa-frown-o
												No hay Usuarios.
			
		.col-lg-3.col-md-3{ style: "padding:0px;"}
			.show-wrapper
				.show-head
				.show-body
					.panel.panel-default
						.panel-heading{ style: "height:55px;" }
							.actions{ "ng-show" => "object_data" }
								.title.pull-left{ style: "margin-top:6px;" }
									%i.fa.fa-user
									Usuario - {{ object_data.id }}
								- if can? :destroy, User
									= link_to "{{destroy_path(object_data.id)}}", title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar este usuario?' }, class: "btn btn-default btn-action pull-right", "ng-show" => "object_data" do
										%i.fa.fa-remove
								- if can? :edit, User
									= link_to "{{edit_path(object_data.id)}}", title: t('admin.actions.edit'), class: "btn btn-default btn-action pull-right", "ng-show" => "object_data", style: "margin-right:3px;" do
										%i.fa.fa-pencil
							.actions{ "ng-show" => "!object_data", style: "margin-top:6px;" }
								%i.fa.fa-user
								Usuario
						.panel-body
							.data{ style: "height: {{windowHeight-104}}px;" }
								.attributes{ "ng-show" => "object_data" }
									%label Nombre: 
									{{object_data.name}}
									%br
									%label Correo electronico: 
									{{object_data.email}}
									%br/
									%label Rol:
									{{object_data.role_name | titlecase}}
									%br/
									%label Permalink:
									{{object_data.permalink}}
									%br/
									%label Creado:
									{{object_data.created_at | date : format : timezone}}
									%br/
									%label
										Logeado: 
									{{object_data.sign_in_count}} veces.
								.attributes{ "ng-show" => "!object_data"}
									%center
										No se ha seleccionado un usuario para mostrar.
				.show-footer

app/views/users/_view_sm_xs.html.haml
- if can? :new, User
	= link_to new_user_path, class: "float-button" do
		%i.fa.fa-plus
.panel.panel-default{style:"margin-top:50px"}
	.panel-header
		.paginator{ "ng-show" => "objects.length > 0"}
			%center
				Página {{currentPage+1}} de {{numberOfPages()}}
			%a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
				%i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
			%a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
				%i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
	.panel-body#grid{ style: "border-right: 1px solid #e7e7e7;padding-left: 0px;padding-right: 0px;border-top-width: 36px;" }	
		%table.grid{style: "width:100%;"}
			%tbody
				%tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object)", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize"}
					- if can? :delete, User
						%td{ width: "1px;" }
							.checkboxFour
								%input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
								%label{ for: "check-{{object.id}}" }
									%span
					%td
						= link_to "{{show_path(object.id)}}", style: "width:100%;" do
							{{ object.name }}
					%td 
						= link_to "{{show_path(object.id)}}", style: "width:100%;" do
							{{ object.role_name | titlecase }}
				%tr{"ng-show" => "!objects.length"}
					%td{:style => "width:100%"}
						%center
							%i.fa.fa-frown-o
							No hay Usuarios.

app/views/users/edit.html.haml
= content_for(:title, "Admin - Usuarios | Editar")
%div{ style: "padding:10px; padding-bottom:0px;"}
	= render 'form'

app/views/users/index.html.haml
= content_for(:title, "Admin - Usuarios")

.view-lg-md.hidden-xs.hidden-sm
	= render "view_lg_md"
.view-sm-xs.hidden-lg.hidden-md
	= render "view_sm_xs"
					

		

app/views/users/new.html.haml
= content_for(:title, "Admin - Usuarios | Nuevo")

%div{ style: "padding:10px; padding-bottom:0px;"}
	= render 'form'

app/views/users/show.html.haml
= content_for(:title, "Admin - Usuarios | #{@user.name}")
- flash.each do |name, msg|
	- if msg.is_a?(String)
		%div.hidden-xs{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", id:"message_alerts"}
			%button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
			= content_tag :div, msg, :id => "flash_#{name}"
%div
	.panel.panel-default{style:"margin-top:50px"}
		.panel-heading#heading-show{style:"padding-top:5px"}
			.actions
				.title.pull-left{ style: "margin-top:8px;" }
					%i.fa.fa-user
					Usuario - 
					= @user.id
				- if can? :destroy, User
					= link_to user_path(@user), title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar este usuario?' }, class: "btn btn-default btn-action pull-right" do
						%i.fa.fa-remove
				- if can? :edit, User
					= link_to  edit_user_path(@user), title: t('admin.actions.edit'), class: "btn btn-default btn-action pull-right", style: "margin-right:3px;" do
						%i.fa.fa-pencil		

		.panel-body#body-show
			%label= t('user.name')+': '
			= @user.name
			%br/
			%label= t('user.email')+': '
			= @user.email
			%br/
			%label= t('user.rol')+': '
			= t("roles.#{@user.roles.first.name}")
			%br/
			%label= t('user.permalink')+': '
			= t("roles.#{@user.permalink}")
			%br/
			%label= t('user.creacion')+': '
			= t("roles.#{@user.created_at}")
			%br/
			%label= t('user.logeado')+': '
			= t("roles.#{@user.sign_in_count}") 
			veces.