config/routes.rb
Rails.application.routes.draw do  

  root to: 'frontend#index'

  resources :reservations, only:[:new, :create]

  get "habitacion/:id", to: "frontend#show_room", as: "show_room"
  
  #get "lugar/:id", to: "frontend#show_place", as: "show_place"

  mount InyxCatalogRails::Engine, :at => '', as: 'catalog'

  devise_for :users, skip: [:registration]

  resources :admin, only: [:index]

  scope :admin, except: [:new, :create] do
    resources :reservations do
      collection do
        post '/delete', to: 'reservations#delete'
        get '/', to: 'reservations#index', as: 'index'
      end
    end
  end
  scope :admin do
  	resources :users do
  		collection do
	  		post '/delete', to: 'users#delete'
  		end
  	end
  end
end

app/models/reservation.rb
require 'elasticsearch/model'
class Reservation < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  before_save :assignments_filter
  before_destroy :assignments_destroy
  #validaciones#####################################
  validates_presence_of :adult, :check_in, :check_out, :pay, :assignments
  validate :valid_date_range_required
  validate :valid_check_in
  validate :validates_rooms
  validates_numericality_of :phone, :adult
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  #Relaciones#######################################
  belongs_to :client
  belongs_to :pay
  has_many :assignments
  has_many :rooms, through: :assignments
  accepts_nested_attributes_for :client
  accepts_nested_attributes_for :assignments
  
	def as_json(options = {})
		{
			id: self.id,
			cedula: self.client.cedula,
			name: self.client.name,
			email: self.email,
			phone: self.phone,
			adult: self.adult,
			children: self.children,
			check_in: self.check_in,
			check_out: self.check_out,
			motive: self.motive,
			pay: pay_name(self.pay_id),
			rooms: room_names(self.assignments),
			created_at: self.created_at,
			status: status_reservation(self.check_in, self.check_out)
		}
	end

	def self.query(query)
    { query: { multi_match:  { query: query, fields: [:cedula, :name, :email, :check_in, :check_out, :pay] , operator: :and }  }, sort: { id: "desc" }, size: Reservation.count }
  end

  #params[:search] is false
  def self.index(current_user)
    Reservation.all.order("created_at DESC")
  end
  #params[:search] is true
  def self.index_search(objects, current_user)
    objects.where("id != #{current_user.id}").order("created_at DESC")
  end

  #params[:search] is true
  def self.index_total(objects, current_user)
    objects.where("id != #{current_user.id}").count
  end

  def pay_name(pay)
		if pay == 0 or pay.nil?
			return "Sin metodo de pago"
		else
			return self.pay.name
		end
	end

	def valid_date_range_required
		unless self.check_in.blank? or self.check_out.blank?
			errors.add(:check_out, "El check-out no puede ser despues del check-in") if Date.parse(self.check_in) > Date.parse(self.check_out)
		end
	end

	def valid_check_in
		unless self.check_in.blank? or self.check_out.blank?
			errors.add(:check_in, "El check-in que usted ingresó no es valido") if Date.parse(self.check_in) < Date.parse(Time.new.to_s)
			errors.add(:check_out, "El check-in que usted ingresó no es valido") if Date.parse(self.check_out) < Date.parse(Time.new.to_s)
		end
	end

	def validates_rooms
		room_hash = []
		self.assignments.each do |assignment|
			unless assignment.quantity.blank?
				room_hash << assignment.quantity
			end
		end
		if room_hash.blank?
			errors.add(:assignments, "Debe elegir una habitación")
		end
	end

	def room_names(assignments)
		assignment_hash = []
		self.assignments.each do |assignment|
			room = Room.find(assignment.room_id)
			assignment_hash << ["#{room.name}", assignment.quantity]
		end
		return assignment_hash.to_a
	end

	def assignments_filter
		self.assignments.each do |assignment|
			if assignment.quantity.blank?
				self.assignments.delete(assignment)
			end			
		end
	end

	def assignments_destroy
		assignments = Assignment.where(reservation_id: self.id)
		assignments.each do |assignment|
			assignment.delete
		end
	end

	def index_elasticsearch_document
    self.__elasticsearch__.index_document
  end

  def status_reservation(check_in, check_out)	
  	check_in = Date.parse(check_in)
  	check_out = Date.parse(check_out)
  	time_now = Date.parse(Time.new.to_s)

		if  time_now < check_in
			return 1
		elsif time_now >= check_in and time_now <= check_out
			return 2
		else
			return 3
		end
	end

  def self.multiple_destroy(ids, current_user)
    Reservation.destroy ids
  end
end

Reservation.import

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:show, :edit, :update, :destroy]
  layout :layout_by_resource
  load_and_authorize_resource
  respond_to :html
  skip_before_filter :verify_authenticity_token  

  def show
    Location.add(request.remote_ip) 
    respond_with(@reservation)
  end

  def new
    Location.add(request.remote_ip) 
    @reservation = Reservation.new
    @reservation.client = Client.new
    @check_in = params[:check_in]
    @check_out = params[:check_out]
    @rooms_type = ["suite", "sencilla", "doble", "familiar", "multiple"]
    respond_with(@reservation)    
  end

  def edit
    Location.add(request.remote_ip) 
  end

  def create
    Location.add(request.remote_ip) 
    puts "Habitaciones #{reservation_params[:assignments_attributes]}"
    @client = Client.find_by_cedula(reservation_params[:client_attributes][:cedula])
    if !@client
      @reservation = Reservation.new(reservation_params)
      if @reservation.save
        ReservationMailer.reservation(@reservation).deliver
        ReservationMailer.client(@reservation).deliver
        flash[:notice] = "Su solicitud de reservación fue realizada exitosamente"
        redirect_to new_reservation_path
      else
        respond_with(@reservation)
      end
    else
      @reservation = Reservation.new(reservation_params)
      @reservation.client = @client
      if @reservation.save
        ReservationMailer.reservation(@reservation).deliver
        ReservationMailer.client(@reservation).deliver
        flash[:notice] = "Su solicitud de reservación fue realizada exitosamente"
        redirect_to new_reservation_path
      else
        respond_with(@reservation)
      end
    end
  end

  def update
    Location.add(request.remote_ip) 
    @reservation.update(reservation_params)
    respond_with(@reservation)
  end

  def destroy
    Location.add(request.remote_ip) 
    @reservation.destroy
    redirect_to index_reservations_path
  end

  private

    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    def reservation_params
      params.require(:reservation).permit(:email, :phone, :adult, :children, :check_in, :check_out, :procedence, :motive, :pay_id, assignments_attributes:[:room_id, :reservation_id, :quantity], client_attributes: [:name, :cedula])
    end

    def layout_by_resource
      if action_name == "new" or action_name == "create"
        "frontend/application"
      else
        "admin/application"
      end
    end

end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.haml
- if flash[:notice]
  .notice.alert.alert-success.alert-dismissible{:role => "alert"}
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} &times;
    = flash[:notice].html_safe
= simple_form_for(@reservation) do |f|
  .form-inputs    
    %h2
      DATOS PERSONALES
    .inputs-reservation
      = f.simple_fields_for :client do |c|
        .row
          .col-lg-6
            = c.input :name, label:false, placeholder: "Nombre y Apellido (Requerido)" 
          .col-lg-6
            = c.input :cedula, label:false, placeholder: "N° Cédula o Pasaporte (Requerido)"
        .row
          .col-lg-6
            = f.input :email, label:false, placeholder: "Email" 
          .col-lg-6
            = f.input :phone, label:false, placeholder: "Teléfono"
    %h2
      DATOS DE RESERVACIÓN
    .inputs-reservation 
      .row
        .col-lg-6
          = f.input :adult, label:false, placeholder: "N° Adultos (Requerido)", input_html:{type:"number", min: "0"}
        .col-lg-6
          = f.input :children, label:false, placeholder: "N° Niños", input_html:{type:"number", min: "0"}
      .row
        .col-lg-6
          = f.input :check_in, label:false, placeholder: "Check in (Requerido)", readonly: true, input_html: { value: "#{@check_in}" }
          %i.fa.fa-calendar
        .col-lg-6
          = f.input :check_out, label:false, placeholder: "Check out (Requerido)", readonly: true, input_html: { value: "#{@check_out}"}
          %i.fa.fa-calendar
      .row
        .col-lg-12
          = f.input :procedence, label:false, placeholder: "Procedencia"
      .row
        .col-lg-12
          = f.input :motive, label:false, placeholder: "Motivo"
    %h2
      SELECCIONAR HABITACIÓN
    .room-inputs
      %p.help-inline
        - if @reservation.errors[:assignments].any?
          = "#{@reservation.errors[:assignments].first}".html_safe 
      .row
        - Room.all.each_with_index do |room, i|
          .room.col-sm-12
            = f.simple_fields_for :assignments, @reservation.assignments.build do |r|
              %a.btn.btn-room{onclick: "quantity(#{room.id})"}
                #image-room{class: "check-#{@rooms_type[i]}"}
                  = r.input :room_id, label: false, :collection => [[room.name, room.id]], :as => :check_boxes, include_hidden: false, input_html: { name: "reservation[assignments_attributes][#{i}][room_id]"}  
                .image-room-mask{id: "mask-#{room.id}"}
                  %p
                    = I18n.transliterate(room.name).upcase
              .quantity{id: "id-#{room.id}"}
                = r.input :quantity, label:false, placeholder: "Cantidad"        
              
    %h2
      MÉTODO DE PAGO
    .inputs-reservation
      .row
        .col-lg-6
          = f.association :pay, label:false, include_blank: "- Tipo de pago (Requerido) -"
    
  %br
  %br
  %br
  .row
    .col-lg-3
      .form-actions
        = f.button :submit, value: "ENVIAR RESERVACIÓN", class: "btn-reservation"

 
  

app/views/reservations/_view_lg_md.html.haml
%div{ 'ng-init'=>"init(#{@objects.to_json}, '/admin/reservations', '#{params[:search]}', #{@total_rows}, #{Kaminari.config.default_per_page})", "resize" => "" }
  .grid-content
    .col-lg-9.col-md-9{ style: "padding:0px;" } 
      .list-wrapper
        .panel.panel-default
          - flash.each do |name, msg|
            - if msg.is_a?(String)
              %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'} pull-right", id: "message_alerts"}
                %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
                = content_tag :div, msg, :id => "flash_#{name}"
          .panel-heading#list-heading
            %a.btn.btn-default.btn-action{"ng-click" => "refresh()", "ng-disabled" => "pagesItemsSelected[currentPageServer].length != 0", :title => t("admin.buttons.refresh") }
              %i.fa.fa-refresh#icon-refresh{'ng-show'=>"!loadingRefresh"}
              %i.fa.fa-refresh.fa-spin{'ng-show'=>"loadingRefresh"}
            - if can? :delete, Reservation
              %a.btn.btn-default.btn-action{"ng-show" => "objects.length", "ng-click" => "allSelected(objects)", :title => t("admin.buttons.select_all") }
                %i.fa.fa-square-o{"ng-show" => "!btnDelete"}
                %i.fa.fa-check-square-o{ "ng-show" => "btnDelete" } 
              %a.btn.btn-default.btn-action#btn-delete{ "ng-show" => "btnDelete", "ng-click" => "destroy('¿Estas seguro de querer eliminar las reservas seleccionadas?')", :title => t("admin.buttons.trash") }
                %i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingDelete" }
                %i.fa.fa-trash-o{ 'ng-show' => "!loadingDelete" }
            .paginator.pull-right{ "ng-show" => "objects.length > 0"}
              %button.btn.btn-default.pull-right.hidden-xs{'disabled'=>"", style:"color:#000; margin-left:3px;"}
                Página {{currentPage+1}} de {{numberOfPages()}}
              %a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
                %i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
                %i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
              %a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
                %i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
                %i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
          .panel-body{ style: "border-right: 1px solid #e7e7e7;" }
            #table-scroll
              %table.grid{style: "width:100%"}
                %tbody
                  %tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object)", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize"}
                    - if can? :delete, Reservation
                      %td{ width: "1px;" }
                        .checkboxFour
                          %input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
                          %label{ for: "check-{{object.id}}" }
                            %span
                    %td # {{ object.id }}
                    %td {{ object.name }}
                    %td {{ object.check_in }}
                    %td {{ object.check_out }}
                    %td{'ng-if'=>'object.status==1'}
                      .status{style: "color:rgb(160, 187, 213);font-size: 30px"}
                        %i.fa.fa-clock-o
                    %td{'ng-if'=>'object.status==2'}
                      .status{style: "color:rgb(121, 219, 121);font-size: 30px"}
                        %i.fa.fa-clock-o
                    %td{'ng-if'=>'object.status==3'}
                      .status{style: "color:rgb(237, 123, 123);font-size: 30px"}
                        %i.fa.fa-clock-o
                  
                  %tr{"ng-show" => "!objects.length"}
                    %td{:style => "width:100%"}
                      %center
                        %i.fa.fa-frown-o
                        No hay Reservaciones.
      
    .col-lg-3.col-md-3{ style: "padding:0px;"}
      .show-wrapper
        .show-head
        .show-body
          .panel.panel-default
            .panel-heading{ style: "height:55px;" }
              .actions{ "ng-show" => "object_data" }
                .title.pull-left{ style: "margin-top:6px;" }
                  %i.fa.fa-credit-card
                  Reservación - {{ object_data.id }}
                - if can? :destroy, Reservation
                  = link_to "{{destroy_path(object_data.id)}}", title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar este usuario?' }, class: "btn btn-default btn-action pull-right", "ng-show" => "object_data" do
                    %i.fa.fa-remove
              .actions{ "ng-show" => "!object_data", style: "margin-top:6px;" }
                %i.fa.fa-calendar
                Reservaciones
            .panel-body
              .data{ style: "height: {{windowHeight-104}}px;" }
                .attributes{ "ng-show" => "object_data" }
                  %label Nombre del cliente: 
                  {{object_data.name}}
                  %br
                  %label Cedula: 
                  {{object_data.cedula}}
                  %br
                  %label Email: 
                  {{object_data.email}}
                  %br
                  %label Telefono: 
                  {{object_data.phone}}
                  %br
                  %div{'ng-if'=>'object_data.adult'}
                    %label Adultos: 
                    {{object_data.adult}}
                    %br
                  %div{'ng-if'=>'object_data.children'}
                    %label Niños: 
                    {{object_data.children}}
                    %br
                  %label Check in: 
                  {{object_data.check_in}}
                  %br
                  %label Check out: 
                  {{object_data.check_out}}
                  %br
                  %div{'ng-repeat'=>'room in object_data.rooms'}
                    %label {{room[0]}}: 
                    {{room[1]}}
                    %br
                  %label Metodo de pago: 
                  {{object_data.pay}}
                  %br
                  %label Fecha de reservación:
                  {{object_data.created_at | date:'dd/M/yyyy H:mm'}}
                  %br
                .attributes{ "ng-show" => "!object_data"}
                  %center
                    No se ha seleccionado una reservación para mostrar.
        .show-footer

app/views/reservations/_view_sm_xs.html.haml
.panel.panel-default{style:"margin-top:50px"}
	.panel-header
		.paginator{ "ng-show" => "objects.length > 0"}
			%center
				Página {{currentPage+1}} de {{numberOfPages()}}
			%a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
				%i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
			%a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
				%i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
	.panel-body#grid{ style: "border-right: 1px solid #e7e7e7;padding-left: 0px;padding-right: 0px;border-top-width: 36px;" }	
		%table.grid{style: "width:100%;"}
			%tbody
				%tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object)", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize"}
					- if can? :delete, Reservation
						%td{ width: "1px;" }
							.checkboxFour
								%input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
								%label{ for: "check-{{object.id}}" }
									%span
					%td
						= link_to "{{show_path(object.id)}}", style: "width:100%;" do
							{{ object.name }}
					%td 
						= link_to "{{show_path(object.id)}}", style: "width:100%;" do
							{{ object.check_in }}
					%td{'ng-if'=>'object.status==1'}
						.status{style: "color:rgb(160, 187, 213);font-size: 30px"}
							%i.fa.fa-clock-o
					%td{'ng-if'=>'object.status==2'}
						.status{style: "color:rgb(121, 219, 121);font-size: 30px"}
							%i.fa.fa-clock-o
					%td{'ng-if'=>'object.status==3'}
						.status{style: "color:rgb(237, 123, 123);font-size: 30px"}
							%i.fa.fa-clock-o
				%tr{"ng-show" => "!objects.length"}
					%td{:style => "width:100%"}
						%center
							%i.fa.fa-frown-o
							No hay reservaciones.

app/views/reservations/edit.html.haml
%h1 Editing reservation

= render 'form'

= link_to 'Show', @reservation
\|
= link_to 'Back', reservations_path

app/views/reservations/index.html.haml
= content_for(:title, "Admin - Reservaciones")

.view-lg-md.hidden-xs.hidden-sm
  = render "view_lg_md"
.view-sm-xs.hidden-lg.hidden-md
  = render "view_sm_xs"

app/views/reservations/new.html.haml
#navigation
	= render 'layouts/frontend/navigation'
#rooms-image
#reservation-form	
	.container
		= render 'form'

app/views/reservations/show.html.haml
= content_for(:title, "Admin - Reservaciones")
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div.hidden-xs{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", id:"message_alerts"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"
%div
  .panel.panel-default{style:"margin-top:50px"}
    .panel-heading#heading-show{style:"padding-top:5px"}
      .actions
        .title.pull-left{ style: "margin-top:8px;" }
          %i.fa.fa-user
          Reservación - 
          = @reservation.id
        - if can? :destroy, Reservation
          = link_to user_path(@reservation), title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar este usuario?' }, class: "btn btn-default btn-action pull-right" do
            %i.fa.fa-remove
        - if can? :edit, Reservation
          = link_to  edit_user_path(@reservation), title: t('admin.actions.edit'), class: "btn btn-default btn-action pull-right", style: "margin-right:3px;" do
            %i.fa.fa-pencil   

    .panel-body#body-show
      %label Nombre: 
      = @reservation.client.name
      %br
      %label Cedula: 
      = @reservation.client.cedula
      %br
      %label Email: 
      = @reservation.client.email
      %br
      %label Teléfono: 
      = @reservation.client.phone
      %br
      %label Adultos: 
      = @reservation.adult
      %br
      %label Niños: 
      = @reservation.children
      %br
      %label Check in: 
      = @reservation.check_in
      %br
      %label Check out: 
      = @reservation.check_out
      %br
      